import type {
  CommandPaletteOption,
  CommandPaletteScope,
} from './components/CommandPalette'

export type CascaderyCommandOption = CommandPaletteOption & {
  aliases: string[]
  scope: CommandPaletteScope
}

export const COMMAND_PALETTE_OPTIONS: CascaderyCommandOption[] = [
  {
    id: 'help',
    title: 'Help',
    description: 'Show keyboard shortcuts and editing tips',
    aliases: ['?', 'shortcuts', 'guide', 'instructions'],
    scope: 'global',
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Keyboard shortcuts',
    description: 'Show canvas keyboard controls',
    aliases: ['?', 'keys', 'hotkeys', 'accessibility'],
    scope: 'global',
  },
  {
    id: 'page-outline',
    title: 'Page outline',
    description: 'Browse Areas in reading order',
    aliases: ['outline', 'contents', 'area list', 'jump'],
    scope: 'page',
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Open editor preferences',
    aliases: ['preferences', 'configure editor', 'options'],
    scope: 'global',
  },
  {
    id: 'page-styles',
    title: 'Page styles',
    description: 'Manage page-wide appearance',
    aliases: ['appearance', 'page settings', 'background', 'theme'],
    scope: 'page',
  },
  {
    id: 'agent-suggestions',
    title: 'Agent suggestions',
    description: 'Review a suggested decision-log patch',
    aliases: ['ai', 'assistant', 'mcp', 'suggestions'],
    scope: 'global',
  },
  {
    id: 'share',
    title: 'Share',
    description: 'Create edit and view-only links',
    aliases: ['copy link', 'invite', 'collaborate', 'links'],
    scope: 'global',
  },
  {
    id: 'agent-connections',
    title: 'Agent connections',
    description: 'Create and revoke scoped MCP tokens for this page',
    aliases: ['mcp tokens', 'agent token', 'connections', 'api access'],
    scope: 'page',
  },
  {
    id: 'history',
    title: 'History',
    description: 'Review recent changes and undo reversible patches',
    aliases: ['timeline', 'changes', 'versions', 'undo'],
    scope: 'global',
  },
  {
    id: 'snapshot-current-state',
    title: 'Snapshot current state',
    description: 'Name the current page state for later comparison or restore',
    aliases: ['version', 'save version', 'named snapshot', 'milestone'],
    scope: 'page',
  },
  {
    id: 'compare-snapshots',
    title: 'Compare snapshots',
    description: 'Open snapshot history and compare a saved state to live',
    aliases: ['diff', 'visual diff', 'compare versions', 'version diff'],
    scope: 'page',
  },
  {
    id: 'undo',
    title: 'Undo',
    description: 'Undo your latest canvas change in this session',
    aliases: ['revert', 'cmd z', 'ctrl z'],
    scope: 'page',
  },
  {
    id: 'redo',
    title: 'Redo',
    description: 'Redo your latest undone canvas change',
    aliases: ['restore', 'shift cmd z', 'ctrl y'],
    scope: 'page',
  },
  {
    id: 'search-areas',
    title: 'Search Areas...',
    description: 'Find and jump to matching Areas on this page',
    aliases: ['find', 'jump', 'navigate', 'search page'],
    scope: 'page',
  },
  {
    id: 'insert-context-kit',
    title: 'Insert context kit',
    description: 'Start from a developer workflow kit',
    aliases: ['template', 'starter', 'kit', 'implementation map'],
    scope: 'page',
  },
  {
    id: 'agent-handoff',
    title: 'Create agent handoff brief',
    description: 'Preview and copy a structured Markdown brief',
    aliases: ['handoff', 'brief', 'agent brief', 'copy markdown'],
    scope: 'page',
  },
  {
    id: 'agent-journal',
    title: 'Toggle agent journal',
    description: 'Show recent human and agent progress notes',
    aliases: ['journal', 'agent log', 'activity', 'progress'],
    scope: 'page',
  },
  {
    id: 'task-board',
    title: 'Task board',
    description: 'Review task Areas by status and attention needed',
    aliases: ['mission control', 'board', 'tasks', 'kanban', 'agent work'],
    scope: 'page',
  },
  {
    id: 'export-sdd-bundle',
    title: 'Export SDD bundle',
    description: 'Download spec.md, plan.md, and tasks.md',
    aliases: ['sdd', 'spec', 'plan', 'tasks', 'spec kit', 'spec-driven'],
    scope: 'page',
  },
  {
    id: 'copy-sdd-bundle',
    title: 'Copy SDD bundle',
    description: 'Copy the combined spec/plan/tasks Markdown',
    aliases: ['sdd', 'copy spec', 'copy plan', 'copy tasks'],
    scope: 'page',
  },
  {
    id: 'export-spec-kit-bundle',
    title: 'Export Spec Kit bundle',
    description: 'Download a zipped Spec Kit feature directory (spec/plan/tasks)',
    aliases: ['spec kit', 'spec-kit', 'speckit', 'sdd zip', 'feature directory'],
    scope: 'page',
  },
  {
    id: 'insert-ears-ubiquitous',
    title: 'Insert requirement: ubiquitous',
    description: 'EARS scaffold — "The system shall …"',
    aliases: ['ears', 'requirement', 'shall'],
    scope: 'page',
  },
  {
    id: 'insert-ears-event-driven',
    title: 'Insert requirement: event-driven (When)',
    description: 'EARS scaffold — "When <trigger>, the system shall …"',
    aliases: ['ears', 'requirement', 'when', 'trigger'],
    scope: 'page',
  },
  {
    id: 'insert-ears-state-driven',
    title: 'Insert requirement: state-driven (While)',
    description: 'EARS scaffold — "While <state>, the system shall …"',
    aliases: ['ears', 'requirement', 'while', 'state'],
    scope: 'page',
  },
  {
    id: 'insert-ears-optional-feature',
    title: 'Insert requirement: optional feature (Where)',
    description: 'EARS scaffold — "Where <feature>, the system shall …"',
    aliases: ['ears', 'requirement', 'where', 'optional'],
    scope: 'page',
  },
  {
    id: 'insert-ears-unwanted-behavior',
    title: 'Insert requirement: unwanted behavior (If/Then)',
    description: 'EARS scaffold — "If <condition>, then the system shall …"',
    aliases: ['ears', 'requirement', 'if then', 'error case'],
    scope: 'page',
  },
  {
    id: 'show-uncovered-requirements',
    title: 'Show uncovered requirements',
    description: 'Select requirement Areas with no implementing task link',
    aliases: ['coverage', 'traceability', 'uncovered', 'requirements'],
    scope: 'page',
  },
  {
    id: 'import-mermaid',
    title: 'Import Mermaid…',
    description: 'Paste a Mermaid flowchart and convert it to Areas and links',
    aliases: ['mermaid', 'diagram', 'flowchart', 'paste diagram'],
    scope: 'page',
  },
  {
    id: 'copy-as-mermaid',
    title: 'Copy as Mermaid',
    description: 'Copy the selection (or page) as a Mermaid flowchart block',
    aliases: ['mermaid', 'diagram', 'export diagram', 'flowchart'],
    scope: 'page',
  },
  {
    id: 'import-sdd',
    title: 'Import spec/plan Markdown…',
    description: 'Lay out spec/plan/tasks Markdown as reviewable Areas',
    aliases: ['sdd', 'import spec', 'import plan', 'import tasks', 'paste spec'],
    scope: 'page',
  },
  {
    id: 'set-area-type',
    title: 'Set Area type',
    description: 'Choose metadata for the selected Area',
    aliases: ['type', 'metadata', 'status', 'area kind'],
    scope: 'area',
  },
  {
    id: 'link-selected-area',
    title: 'Link selected Area',
    description: 'Connect the selected Area to another Area',
    aliases: [
      'link area',
      'relationship',
      'connect',
      'reference',
      'arrow',
      'schema',
      'foreign key',
    ],
    scope: 'area',
  },
  {
    id: 'nest-selected-area',
    title: 'Nest selected Area',
    description: 'Move the selected Area inside another Area',
    aliases: ['child area', 'parent area', 'container', 'group area'],
    scope: 'area',
  },
  {
    id: 'unnest-selected-area',
    title: 'Unnest selected Area',
    description: 'Move the selected Area back to the main canvas',
    aliases: ['remove parent', 'top level', 'ungroup area'],
    scope: 'area',
  },
  {
    id: 'add-child-area',
    title: 'Add child Area',
    description: 'Create a new Area inside the selected Area',
    aliases: ['new child', 'inside area', 'contained note'],
    scope: 'area',
  },
  {
    id: 'add-evidence',
    title: 'Add evidence to selected Area',
    description: 'Attach a file, URL, issue, PR, commit, or command reference',
    aliases: ['ref', 'reference', 'anchor', 'file reference', 'evidence'],
    scope: 'area',
  },
  {
    id: 'comment-selected-area',
    title: 'Comment on selected Area',
    description: 'Open the comment thread for the selected Area',
    aliases: ['comment', 'comments', 'thread', 'annotation'],
    scope: 'area',
  },
  {
    id: 'align-left',
    title: 'Align left',
    description: 'Align selected Areas to the left edge',
    aliases: ['left align', 'line up left'],
    scope: 'area',
  },
  {
    id: 'align-right',
    title: 'Align right',
    description: 'Align selected Areas to the right edge',
    aliases: ['right align', 'line up right'],
    scope: 'area',
  },
  {
    id: 'align-top',
    title: 'Align top',
    description: 'Align selected Areas to the top edge',
    aliases: ['top align', 'line up top'],
    scope: 'area',
  },
  {
    id: 'align-bottom',
    title: 'Align bottom',
    description: 'Align selected Areas to the bottom edge',
    aliases: ['bottom align', 'line up bottom'],
    scope: 'area',
  },
  {
    id: 'align-center-x',
    title: 'Align horizontal centers',
    description: 'Align selected Areas through the vertical centerline',
    aliases: ['center horizontally', 'align middle x'],
    scope: 'area',
  },
  {
    id: 'align-center-y',
    title: 'Align vertical centers',
    description: 'Align selected Areas through the horizontal centerline',
    aliases: ['center vertically', 'align middle y'],
    scope: 'area',
  },
  {
    id: 'distribute-horizontal',
    title: 'Distribute horizontally',
    description: 'Evenly space selected Areas from left to right',
    aliases: ['space horizontally', 'horizontal spacing'],
    scope: 'area',
  },
  {
    id: 'distribute-vertical',
    title: 'Distribute vertically',
    description: 'Evenly space selected Areas from top to bottom',
    aliases: ['space vertically', 'vertical spacing'],
    scope: 'area',
  },
  {
    id: 'toggle-snap-grid',
    title: 'Toggle snap grid',
    description: 'Snap Area movement and resizing to page grid',
    aliases: ['grid', 'snap', 'alignment'],
    scope: 'page',
  },
  {
    id: 'insert-image',
    title: 'Insert image',
    description: 'Add a movable image to the page',
    aliases: ['image', 'photo', 'picture', 'upload image'],
    scope: 'page',
  },
  {
    id: 'insert-gif',
    title: 'Insert GIF',
    description: 'Search GIPHY and insert a GIF image Area',
    aliases: ['gif', 'giphy', 'reaction', 'media'],
    scope: 'page',
  },
  {
    id: 'insert-benchmark-content',
    title: 'Insert benchmark content',
    description: 'Replace this page with generated scale-test Areas',
    aliases: ['benchmark', 'performance', 'stress test', 'large canvas'],
    scope: 'page',
  },
  {
    id: 'zoom-in',
    title: 'Zoom in',
    description: 'Increase canvas zoom',
    aliases: ['closer', 'magnify', 'increase zoom'],
    scope: 'page',
  },
  {
    id: 'zoom-out',
    title: 'Zoom out',
    description: 'Decrease canvas zoom',
    aliases: ['farther', 'decrease zoom', 'reduce zoom'],
    scope: 'page',
  },
  {
    id: 'reset-zoom',
    title: 'Reset zoom',
    description: 'Return the canvas to 100%',
    aliases: ['actual size', '100%', 'normal zoom'],
    scope: 'page',
  },
  {
    id: 'zoom-to-fit',
    title: 'Zoom to fit page',
    description: 'Fit all Areas in view',
    aliases: ['fit page', 'fit canvas', 'show all'],
    scope: 'page',
  },
  {
    id: 'zoom-to-selection',
    title: 'Zoom to selection',
    description: 'Center the selected Area',
    aliases: ['selected area', 'center selection', 'focus area'],
    scope: 'area',
  },
  {
    id: 'toggle-color-scheme',
    title: 'Toggle color scheme',
    description: 'Cycle the editor chrome between System, Light, and Dark',
    aliases: ['dark mode', 'light mode', 'theme', 'appearance', 'color scheme'],
    scope: 'global',
  },
  {
    id: 'toggle-telemetry',
    title: 'Toggle usage telemetry',
    description:
      'Enable or disable anonymous usage counts for this browser',
    aliases: [
      'disable usage telemetry',
      'enable usage telemetry',
      'privacy',
      'analytics',
      'opt out',
    ],
    scope: 'global',
  },
]
