import type {
  CommandPaletteOption,
  CommandPaletteScope,
} from './components/CommandPalette'

export type CascaderyCommandOption = CommandPaletteOption & {
  aliases: string[]
  scope: CommandPaletteScope
}

export const COMMAND_PALETTE_OPTIONS: CascaderyCommandOption[] = [
  {
    id: 'help',
    title: 'Help',
    description: 'Show keyboard shortcuts and editing tips',
    aliases: ['?', 'shortcuts', 'guide', 'instructions'],
    scope: 'global',
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Open editor preferences',
    aliases: ['preferences', 'configure editor', 'options'],
    scope: 'global',
  },
  {
    id: 'page-styles',
    title: 'Page styles',
    description: 'Manage page-wide appearance',
    aliases: ['appearance', 'page settings', 'background', 'theme'],
    scope: 'page',
  },
  {
    id: 'agent-suggestions',
    title: 'Agent suggestions',
    description: 'Review a suggested decision-log patch',
    aliases: ['ai', 'assistant', 'mcp', 'suggestions'],
    scope: 'global',
  },
  {
    id: 'share',
    title: 'Share',
    description: 'Create edit and view-only links',
    aliases: ['copy link', 'invite', 'collaborate', 'links'],
    scope: 'global',
  },
  {
    id: 'history',
    title: 'History',
    description: 'Review recent changes and undo reversible patches',
    aliases: ['timeline', 'changes', 'versions', 'undo'],
    scope: 'global',
  },
  {
    id: 'search-areas',
    title: 'Search Areas...',
    description: 'Find and jump to matching Areas on this page',
    aliases: ['find', 'jump', 'navigate', 'search page'],
    scope: 'page',
  },
  {
    id: 'insert-context-kit',
    title: 'Insert context kit',
    description: 'Start from a developer workflow kit',
    aliases: ['template', 'starter', 'kit', 'implementation map'],
    scope: 'page',
  },
  {
    id: 'agent-handoff',
    title: 'Create agent handoff brief',
    description: 'Preview and copy a structured Markdown brief',
    aliases: ['handoff', 'brief', 'agent brief', 'copy markdown'],
    scope: 'page',
  },
  {
    id: 'set-area-type',
    title: 'Set Area type',
    description: 'Choose metadata for the selected Area',
    aliases: ['type', 'metadata', 'status', 'area kind'],
    scope: 'area',
  },
  {
    id: 'link-selected-area',
    title: 'Link selected Area',
    description: 'Connect the selected Area to another Area',
    aliases: [
      'link area',
      'relationship',
      'connect',
      'reference',
      'arrow',
      'schema',
      'foreign key',
    ],
    scope: 'area',
  },
  {
    id: 'nest-selected-area',
    title: 'Nest selected Area',
    description: 'Move the selected Area inside another Area',
    aliases: ['child area', 'parent area', 'container', 'group area'],
    scope: 'area',
  },
  {
    id: 'unnest-selected-area',
    title: 'Unnest selected Area',
    description: 'Move the selected Area back to the main canvas',
    aliases: ['remove parent', 'top level', 'ungroup area'],
    scope: 'area',
  },
  {
    id: 'add-child-area',
    title: 'Add child Area',
    description: 'Create a new Area inside the selected Area',
    aliases: ['new child', 'inside area', 'contained note'],
    scope: 'area',
  },
  {
    id: 'add-evidence',
    title: 'Add evidence to selected Area',
    description: 'Attach a file, URL, issue, PR, commit, or command reference',
    aliases: ['ref', 'reference', 'anchor', 'file reference', 'evidence'],
    scope: 'area',
  },
  {
    id: 'comment-selected-area',
    title: 'Comment on selected Area',
    description: 'Open the comment thread for the selected Area',
    aliases: ['comment', 'comments', 'thread', 'annotation'],
    scope: 'area',
  },
  {
    id: 'align-left',
    title: 'Align left',
    description: 'Align selected Areas to the left edge',
    aliases: ['left align', 'line up left'],
    scope: 'area',
  },
  {
    id: 'align-right',
    title: 'Align right',
    description: 'Align selected Areas to the right edge',
    aliases: ['right align', 'line up right'],
    scope: 'area',
  },
  {
    id: 'align-top',
    title: 'Align top',
    description: 'Align selected Areas to the top edge',
    aliases: ['top align', 'line up top'],
    scope: 'area',
  },
  {
    id: 'align-bottom',
    title: 'Align bottom',
    description: 'Align selected Areas to the bottom edge',
    aliases: ['bottom align', 'line up bottom'],
    scope: 'area',
  },
  {
    id: 'align-center-x',
    title: 'Align horizontal centers',
    description: 'Align selected Areas through the vertical centerline',
    aliases: ['center horizontally', 'align middle x'],
    scope: 'area',
  },
  {
    id: 'align-center-y',
    title: 'Align vertical centers',
    description: 'Align selected Areas through the horizontal centerline',
    aliases: ['center vertically', 'align middle y'],
    scope: 'area',
  },
  {
    id: 'distribute-horizontal',
    title: 'Distribute horizontally',
    description: 'Evenly space selected Areas from left to right',
    aliases: ['space horizontally', 'horizontal spacing'],
    scope: 'area',
  },
  {
    id: 'distribute-vertical',
    title: 'Distribute vertically',
    description: 'Evenly space selected Areas from top to bottom',
    aliases: ['space vertically', 'vertical spacing'],
    scope: 'area',
  },
  {
    id: 'toggle-snap-grid',
    title: 'Toggle snap grid',
    description: 'Snap Area movement and resizing to page grid',
    aliases: ['grid', 'snap', 'alignment'],
    scope: 'page',
  },
  {
    id: 'insert-image',
    title: 'Insert image',
    description: 'Add a movable image to the page',
    aliases: ['image', 'photo', 'picture', 'upload image'],
    scope: 'page',
  },
  {
    id: 'insert-gif',
    title: 'Insert GIF',
    description: 'Search GIPHY and insert a GIF image Area',
    aliases: ['gif', 'giphy', 'reaction', 'media'],
    scope: 'page',
  },
  {
    id: 'zoom-in',
    title: 'Zoom in',
    description: 'Increase canvas zoom',
    aliases: ['closer', 'magnify', 'increase zoom'],
    scope: 'page',
  },
  {
    id: 'zoom-out',
    title: 'Zoom out',
    description: 'Decrease canvas zoom',
    aliases: ['farther', 'decrease zoom', 'reduce zoom'],
    scope: 'page',
  },
  {
    id: 'reset-zoom',
    title: 'Reset zoom',
    description: 'Return the canvas to 100%',
    aliases: ['actual size', '100%', 'normal zoom'],
    scope: 'page',
  },
  {
    id: 'zoom-to-fit',
    title: 'Zoom to fit page',
    description: 'Fit all Areas in view',
    aliases: ['fit page', 'fit canvas', 'show all'],
    scope: 'page',
  },
  {
    id: 'zoom-to-selection',
    title: 'Zoom to selection',
    description: 'Center the selected Area',
    aliases: ['selected area', 'center selection', 'focus area'],
    scope: 'area',
  },
]
